Back End Repeating Event
varvind/BMES pull request #15
Opened 2021-03-22 10:13 UTC by rhrussell

Code Coverage (any file relating to event)  - 100%
Rubocop - no offenses

2021-03-22 16:07 UTC, varvind requested changes

2021-03-22 16:07 UTC, varvind commented on app/admin/events.rb
> +  controller do
nitpicking, but i would probably add some comments, like just explaining whats going on, at first glance its not super obvious to someone who hasnt looked at the code before

2021-03-22 16:07 UTC, varvind commented on app/admin/events.rb
>    end
did you remove "actions" from this block?

2021-03-22 16:36 UTC, varvind requested changes

2021-03-22 16:36 UTC, varvind commented on app/admin/events.rb
> +        (1..weeks).each do |_i|
This should be from 0..weeks because you need to include the current week

2021-03-22 22:35 UTC, varvind approved these changes
Approved once you comment the test file

2021-03-22 22:36 UTC, varvind requested changes
Make sure to handle case where user picks date before the current date

2021-03-22 23:33 UTC, keithbryant3 approved these changes
Everything looks good as far as I can tell.

2021-03-23 04:33 UTC, keithbryant3 approved these changes
Everything still looks good.

2021-04-02 05:52 UTC, varvind requested changes
Overall code looks good, gonna do some more heroku tests but left a few comments

2021-04-02 05:52 UTC, varvind commented on app/admin/events.rb
> +        # if !event.valid? # checks to see if event is successfully created and valid
get rid of commented code

2021-04-02 05:52 UTC, varvind commented on app/admin/events.rb
> +            # if !event.valid? # checks to see if event is successfully created and valid
here too get rid of the commented code

2021-04-02 20:18 UTC, varvind requested changes
Functionality is good, fix that one small change then ill approve! Good job

2021-04-02 20:18 UTC, varvind commented on app/admin/events.rb
> +        redirect_to '/admin/events/new', flash: { error: 'Error: Please Enter Values in Required Fields.' }
This should say something like 'Error: Please Enter Values in All Fields

2021-04-02 20:18 UTC, varvind commented on spec/events_spec.rb
> +      expect(page).to have_content('Error: Please Enter Values in Required Fields.')
change this to the previous comment i mentioned

2021-04-02 20:44 UTC, keithbryant3 approved these changes
Everything looks fine to me.

2021-04-02 20:48 UTC, varvind approved these changes

2021-04-02 23:11 UTC, merged