Calendar
varvind/BMES pull request #16
Opened 2021-03-22 22:09 UTC by burdick-alex

added calendar feature

2021-03-23 02:58 UTC, rhrussell approved these changes
Just tried to open deployment on Heroku and all it shows is an error right from the beginning. Fix that then I can look at the other stuff.

2021-03-23 03:23 UTC, rhrussell requested changes
Just tried to open deployment on Heroku and all it shows is an error. Fix that then I can see the rest of your deployment. But your code on surface level looks fine, just need to fix that error.

2021-04-04 19:05 UTC, varvind requested changes
Overall looks good, just some small things to make things neater

2021-04-04 19:05 UTC, varvind commented on app/javascript/packs/application.js
> +
Probably want to get rid of these extra line breaks

2021-04-04 19:05 UTC, varvind commented on app/views/layouts/application.html.erb
> +
get rid of extra line break

2021-04-04 19:05 UTC, varvind commented on app/views/layouts/application.html.erb
> +
same here

2021-04-04 19:05 UTC, varvind commented on spec/api_spec.rb
>      it 'Valid' do
maybe comment what this line means, seems kinda confusing at first glance

2021-04-04 19:05 UTC, varvind commented on spec/api_spec.rb
> +      travel_to Time.zone.local(2025, 1, 1, 0o1, 0o4, 44)
same here

2021-04-04 19:05 UTC, varvind commented on spec/calendar_spec.rb
> +      travel_to Time.zone.local(2020, 3, 13, 0o1, 0o4, 44)
same here

2021-04-04 19:05 UTC, varvind commented on spec/calendar_spec.rb
> +      travel_to Time.zone.local(2020, 3, 13, 0o1, 0o4, 44)
here too

2021-04-04 19:05 UTC, varvind commented on spec/routes_spec.rb
> +      travel_to Time.zone.local(2025, 1, 1, 0o1, 0o4, 44)
here

2021-04-04 19:05 UTC, varvind commented on spec/routes_spec.rb
> +      travel_to Time.zone.local(2025, 1, 1, 0o1, 0o4, 44)
here

2021-04-04 19:05 UTC, varvind commented on spec/routes_spec.rb
> +      travel_to Time.zone.local(2025, 1, 1, 0o1, 0o4, 44)
here

2021-04-04 19:05 UTC, varvind commented on spec/routes_spec.rb
> +      travel_to Time.zone.local(2025, 1, 1, 0o1, 0o4, 44)
here

2021-04-04 19:05 UTC, varvind commented on spec/tests_spec.rb
> +      travel_to Time.zone.local(2025, 11, 1, 0o1, 0o4, 44)
here and the rest in the project :)

2021-04-04 19:05 UTC, varvind commented on spec/tests_spec.rb
> +      # expect(page).to have_content('Event Title')
get rid of these commented bits

2021-04-04 21:45 UTC, varvind approved these changes
Everything looks good and all functionality tested on heroku

2021-04-05 01:40 UTC, keithbryant3 approved these changes
Everything seems to be good, though it would probably look a little better if you could get some padding at the bottom of the calendar so it isn't flush against the bottom of the page.

2021-04-05 02:37 UTC, rhrussell approved these changes
Everything looks good with the code and on Heroku. What I would suggest to do later on is to make it to where there is some space at the bottom between the calendar and the bottom of the page. That way the calendar is not right up against the bottom of the page. But other than that style critique, looks great. Good job!

2021-04-05 02:38 UTC, merged