Back end event sign in controller update
varvind/BMES pull request #25
Opened 2021-04-23 06:16 UTC by rhrussell

Did some testing but make sure you guys test as well just to be safe. There are no offenses with Rubocop and code coverage is still at 100%, but make sure you guys read the code just to make sure I did not miss any edge cases when it comes to checking into an event with the code and the tests.

2021-04-23 17:28 UTC, varvind reviewed
CSV feature, repeating events, and individual event seem to work fine, still need to test user profile and events late at night

2021-04-23 17:32 UTC, varvind reviewed
Details page, event sign in and user profile work well

2021-04-23 17:35 UTC, varvind requested changes
Nice, code looks good, just one small thing to add and ill continue to test

2021-04-23 17:35 UTC, varvind commented on app/admin/events.rb
> +      newstarttime += 5.hours
probably want to add a comment here on why we chose to do this

2021-04-25 23:31 UTC, burdick-alex requested changes
Doesn't seem to be working on heroku, but some minor things. Either uncomment these lines or remove them before merging

2021-04-25 23:31 UTC, burdick-alex commented on spec/routes_spec.rb
> +      # path2 = "//a[@href='/events/new?event_id=" + event2.id.to_s + "']"
Be sure to uncomment or delete these comments before finishing and merging

2021-04-25 23:31 UTC, burdick-alex commented on spec/routes_spec.rb
> +      # find(:xpath, path2).click
Be sure to uncomment or delete these comments before finishing and merging

2021-04-25 23:31 UTC, burdick-alex commented on spec/routes_spec.rb
> +      # event2.destroy
Be sure to uncomment or delete these comments before finishing and merging

2021-04-26 01:55 UTC, varvind approved these changes
Nice job!

2021-04-26 08:28 UTC, burdick-alex approved these changes
looks good

2021-04-26 08:29 UTC, merged