Keith Bryant patch 1
varvind/BMES pull request #4
Opened 2021-02-26 23:34 UTC by keithbryant3

2021-02-28 00:38 UTC, varvind requested changes
Looks good on the live website! Super nitpicky but some of the tabs and stuff look off. Run rubocop and make sure the styling is correct

2021-02-28 00:44 UTC, varvind requested changes
Also make sure this doesn't break any tests

2021-02-28 11:07 UTC, rhrussell approved these changes

2021-03-05 16:55 UTC, varvind approved these changes
Looks good! Good job on the tests. The only thing i fixed was rubocop errors but other than that good work, code looks great.

2021-03-07 02:46 UTC, merged